**Word Embedding using Keras**

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
# sentance 
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
# Defining Dictionary
voc_size = 10000

**One Hot Represantation**

In [8]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
# Priting index of each word
print(onehot_repr)

[[3945, 7936, 5020, 5216], [3945, 7936, 5020, 2154], [3945, 3925, 5020, 426], [3067, 7042, 9724, 6315, 6187], [3067, 7042, 9724, 6315, 2317], [2605, 3945, 4562, 5020, 2757], [4042, 9490, 5454, 6315]]


## **Word Embedding Represntation**

In [10]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
# setting the sentance length
sent_length = 8

embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen = sent_length)

print(embedded_docs)

[[   0    0    0    0 3945 7936 5020 5216]
 [   0    0    0    0 3945 7936 5020 2154]
 [   0    0    0    0 3945 3925 5020  426]
 [   0    0    0 3067 7042 9724 6315 6187]
 [   0    0    0 3067 7042 9724 6315 2317]
 [   0    0    0 2605 3945 4562 5020 2757]
 [   0    0    0    0 4042 9490 5454 6315]]


In [13]:
# number of features 
f = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size,f,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[ 3.70217822e-02  3.84441875e-02  2.21371315e-02 -1.10362284e-02
   -4.85803746e-02  1.66947283e-02 -2.84399390e-02 -1.15089491e-03
   -1.06077790e-02  4.02299426e-02]
  [ 3.70217822e-02  3.84441875e-02  2.21371315e-02 -1.10362284e-02
   -4.85803746e-02  1.66947283e-02 -2.84399390e-02 -1.15089491e-03
   -1.06077790e-02  4.02299426e-02]
  [ 3.70217822e-02  3.84441875e-02  2.21371315e-02 -1.10362284e-02
   -4.85803746e-02  1.66947283e-02 -2.84399390e-02 -1.15089491e-03
   -1.06077790e-02  4.02299426e-02]
  [ 3.70217822e-02  3.84441875e-02  2.21371315e-02 -1.10362284e-02
   -4.85803746e-02  1.66947283e-02 -2.84399390e-02 -1.15089491e-03
   -1.06077790e-02  4.02299426e-02]
  [-3.28242555e-02 -4.47338820e-03  3.15582044e-02  2.86600739e-03
    2.46482827e-02 -4.02861945e-02 -1.34391077e-02  3.15197557e-03
   -4.33285013e-02 -1.32677779e-02]
  [ 4.01367657e-02 -4.94436286e-02  9.60074738e-03 -5.52487373e-03
    1.85844935e-02 -1.67717785e-03  1.52892135e-02  5.41333109e-03
    1.08483918e-